# Generated by Django 4.2.1 on 2023-10-28 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.CharField(max_length=50)),
                ('competition', models.CharField(max_length=50)),
                ('home_team', models.CharField(max_length=50)),
                ('away_team', models.CharField(max_length=50)),
                ('bet', models.CharField(max_length=100)),
                ('odds', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=10)),
                ('start_date', models.DateTimeField()),
                ('last_update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ('-created_at',),
            },
        ),
    ]
